### PR TITLE
Preparation for submission to the master Awesome List

### PR DESCRIPTION
**Pull request by NewAlexandria**
Hi, I was cleaning up my awesome list, and found a few others that are interesting to me — and decided to be a friendly stranger and help prep. 

* Add linting via travis
* fix some links
* remove some dead pages
* added Contrib guide

did not do (but can if you merge this, and need more help)
* add full TOC
* fix other links
* fix table formatting

### CODE REVIEW

**Comment by laughedelic** [comment]
Why do you change `github` to `GitHub` **in URLs**? Is this required by the awesome-lint?

**Comment by NewAlexandria** [comment]
Oddly, yes. I suspect it is a bug with some other aspect of the linting -
as I think that my list didn’t require me to change this for URLs.

Probably that can be reverted and other lints done first.  Then it’ll
probably go away

**Comment by NewAlexandria** [comment]
OK, I made a round of changes during stuff today.  `github.com` did not start linting agnostically, and I filed this issue about it: https://github.com/sindresorhus/awesome-lint/issues/71

It looks like an easy lift. 

If Sindre and others give it a green light, I'd propose this PR incorporates the downcases that are coming. Or you can merge as-is and I or someone can PR the case change later.

**Comment by NewAlexandria** [comment]
That will probably get merged, when figured out.  I found that it is only the case for non-link URLs, which are not in code-quotes.  

- So if you like the format `https://github.com/diimdeep/awesome-split-keyboards/pull/12` for a URL, then it will lint fine.  
- Or I'll just revert the capitalization, `no ticks`, and then the `awesome-list` PR will merge without dispute later.

Let me know

**Comment by NewAlexandria** [comment]
ping/bump, in hopes to close out

**Comment by laughedelic** [comment]
(I'm not a maintainer, I was just passing by...)

**Comment by NewAlexandria** [comment]
@diimdeep ?

**Comment by pvinis** [comment]
I merged this and the other PRs before this to the new [fork](https://github.com/pvinis/awesome-split-keyboards).

**Comment by NewAlexandria** [comment]
🙏

**Pull request merged**
