### PR TITLE
Added Kyria keyboard

### PR DESCRIPTION
**Pull request by splitkb**
After months of development, I feel like the Kyria is finally ready to be shared on your list of awesome keyboards.

Its case files are open source, the keyboard itself is not. The QMK firmware is available in the official QMK repository, and the keyboard will be for sale permanently at splitkb.com and eventual proxies.

### CODE REVIEW

**Comment by kissu** [comment]
I :+1: this one ! :pray:

**Comment by splitkb** [comment]
Hello @diimdeep, what can I do to get this PR accepted?

**Comment by splitkb** [comment]
I wonder if @diimdeep is still around :)

**Comment by pvinis** [comment]
I merged this and the other PRs before this to the new [fork](https://github.com/pvinis/awesome-split-keyboards).

**Pull request merged**
