### PR TITLE
Added Georgi, updated Gergo

### PR DESCRIPTION
**Pull request by germ**

### CODE REVIEW

**Comment by ibnuda** [comment]
Jim, there's no Georgi's config on qmk's repo.
I got 404.

**Comment by germ** [comment]
Hey it's my favorite motherfucker!

There's a open PR on it, that'll be where it shows up in a few days after
it finishes code review!

**Comment by germ** [comment]
And it's now in QMK master! https://github.com/qmk/qmk_firmware/tree/master/keyboards/georgi

**Comment by pvinis** [comment]
I merged this and the other PRs before this to the new [fork](https://github.com/pvinis/awesome-split-keyboards).

**Pull request merged**
